### ISSUE TITLE
NewLogSync mutates global zerolog variables

### ISSUE THREAD

**Issue by ratelle** [go-logr/zerologr#6]
When calling NewLogSync, zerolog.LevelField is mutated. This is problematic when an application uses zerolog as its logger and uses zerologr in order to satisfy a library's requirement to pass a logr implementation. This causes a side effect on the zerolog global state and forces the application to restore global variables.

https://github.com/go-logr/zerologr/blob/master/zerologr.go#L75-L77

**Comment by hn8** [comment]
@ratelle It is a mismatch between logr which uses {v: int} for level and zerolog uses {level: string}. Zerolog's LevelFieldMarshalFunc can only return string. Currently there are 3 ways to work around:
1. Restore global variable as you did.
2. Rename zerolog.LevelFieldName to "lvl", so zerologr doesn't mutate it.

@thockin What is your opinion about adding function to customize NewLogSink to not disabling LevelFieldName ?

**Comment by pohly** [comment]
What happens when `NewLogSink` doesn't touch `zerolog.LevelFieldName`?

Regarding changing `NewLogSink`: it's part of the v1 API and cannot be changed anymore. You can add a `NewLogSinkWithOptions` and make that the more flexible constructor. Ideally it should use functional options. Those avoid some pitfalls that come with using an option struct.

**Comment by hn8** [comment]
@pohly I actually prefer to not mutating global zerolog.LevelFieldName and let user to decide, but @thockin added the line in this [commit](https://github.com/go-logr/zerologr/commit/95fbb4184928d43cfed008953364b2703174d6eb), later I added the check to not mutating when user already change LevelFieldName. In [pion/ion-sfu](https://github.com/pion/ion-sfu), I also need to restore LevelFieldName since it was the expected behavior. 

Since zapr doesn't remove LevelKey with OmitKey, IMHO it is better that zerologr doesn't mutate global zerolog.LevelFieldName. Restoring level field doesn't break v1 logr API since zapr keeps it besides v field.

**Comment by thockin** [comment]
Is the logging output of a library part of that library's API?  Ordinarily I would say no, except this IS the log library,  Any user of zerologr who has written tools assuming a "level" key will be broken if you change this.

I think I agree with @pohly - Add a more flexible constructor and you can even change the defaults on that path.  E.g.`zerologr.NewWithOptions()` (with no options) can change the key.

**Comment by hn8** [comment]
@thockin @pohly I updated the PR with NewWithOptions. But IMHO restoring level field is to fix bug, not breaking API. Come to think about it, for every projects I use zerologr, I have to restore level field which is disabled globally by zerologr for now. API for logr introduces v field with number, but users of zerolog actually expect to see level field in the rest of application doesn't use logr. So IMHO it is a bug that zerologr breaks Zerolog API.

In projects users use zerologr for library accepting logr but use zerolog directly in application code. They all have to work around current zerologr behavior which "remove" zerolog level field, otherwises they can't see level at all in the codepath not using zerologr.

**Comment by hn8** [comment]
@thockin @pohly I updated the PR with NewWithOptions. But IMHO restoring level field is to fix bug, not breaking API, users actually expect to see "level" key which is removed by zerologr. Come to think about it, for every projects I use zerologr, I have to restore level field after each zerologr.New() call. API for logr introduces v field with number, but users of zerolog actually expect to see level field in the rest of application doesn't use logr (and can't change to use logr overnight). So IMHO it is a bug that zerologr breaks Zerolog API.

In projects users use zerologr for library accepting logr but use zerolog directly in application code. They all have to work around current zerologr behavior which "remove" zerolog level field, otherwises they can't see level at all (no level field from zerolog and no v field from zerologr) in the codepath not using zerologr.

**Comment by pohly** [comment]
> Is the logging output of a library part of that library's API? Ordinarily I would say no, except this IS the log library, Any user of zerologr who has written tools assuming a "level" key will be broken if you change this.

My position is that the log format (formatting, standard fields, etc.) is part of the API of a program because that is what people write parsers for. Individual log message (message string, custom data fields for that message) are not part of the API because that would go too far.

> API for logr introduces v field with number, but users of zerolog actually expect to see level field in the rest of application doesn't use logr (and can't change to use logr overnight). So IMHO it is a bug that zerologr breaks Zerolog API.

I can accept the argument that it was a bug that needs to be fixed, but would like to see a better description of what the effect of the bug is. The description of the issue and PR only talks about the code changes, but not what the expected and actual log content is.

**Comment by hn8** [comment]
@pohly Thanks, please see the log out in the example/example_test.go. The PR restores level field which may be redundant for logr since zerologr adds v field, but necessary for non-logr usage of zerolog users.
https://github.com/go-logr/zerologr/pull/7/commits/ba0130a1dcb117067388fda6d5da1d2e3e00bfa9

**Comment by tonglil** [comment]
> The description of the issue and PR only talks about the code changes, but not what the expected and actual log content is.

Sorry to get here late, but I'm using zerolog and I'd like to elaborate what's going on and a potential solution.

The other implementations of Logr output using their implementation's choice of "leveling", see:
- zap: https://go.dev/play/p/ig2lAbmKgbA (using keyless INFO & DEBUG)
- glog: https://go.dev/play/p/kJpTcwZf1ej (using "level"=0)
- logrus: https://go.dev/play/p/w3-G6-hl08c (using level=info)

However, zerologr tries to replace zerolog's `level` field (which is customizable) with `v`, which doesn't happen in the other implementations: https://go.dev/play/p/dqDZR1-zy-N

With this revision, two level keys are now exposed and are kind of confusing to the user and now a part of zerologr's API: both `level` and `v` ("level":"info","v":0)

I propose a configurable option to use zerolog's `level` key (or whatever the user set it as through `zerolog.LevelFieldName`) instead of `v`, set to false to default to keep the current behavior. PR to come...
